name = "solana-devnet-workers"
main = "src/index.ts"
compatibility_date = "2024-10-01"
compatibility_flags = ["nodejs_compat"]

[vars]
SOL_RECIPIENT = "${SOL_RECIPIENT}"
X402_FACILITATOR_URL = "${X402_FACILITATOR_URL}"
